# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ryan
#tagline:          'A Jekyll theme'
description:      'Software Developer and Religious Studies Enthusiast'
url:              rajenkins.me

author:
  name:           'Ryan Jenkins'
  url:            https://rajenkins.me

paginate:         5

# Custom vars

github:
  repo:           https://github.com/poole/hyde
